#!/usr/bin/env bash
# flash_watch.sh — Build and flash Buddhas-Watch firmware to an ESP32-S3
#
# Usage:
#   ./scripts/flash_watch.sh [PORT] [NODE_ID]
#
#   PORT    Serial port (default: /dev/ttyUSB0)
#   NODE_ID Node identifier string written into firmware (default: watch_left)
#
# Examples:
#   ./scripts/flash_watch.sh
#   ./scripts/flash_watch.sh /dev/ttyUSB1 watch_right
#   ./scripts/flash_watch.sh /dev/ttyUSB2 pocket

set -euo pipefail

PORT="${1:-/dev/ttyUSB0}"
NODE_ID="${2:-watch_left}"
FIRMWARE_DIR="$(cd "$(dirname "$0")/.." && pwd)/firmware/esp32-s3"

# ---- colour helpers ----
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()    { echo -e "${GREEN}[flash]${NC} $*"; }
warn()    { echo -e "${YELLOW}[flash]${NC} $*"; }
error()   { echo -e "${RED}[flash]${NC} $*" >&2; exit 1; }

# ---- validate ESP-IDF ----
if [ -z "${IDF_PATH:-}" ]; then
    if [ -f "$HOME/esp/esp-idf/export.sh" ]; then
        warn "Sourcing ESP-IDF from $HOME/esp/esp-idf/export.sh"
        # shellcheck disable=SC1090
        source "$HOME/esp/esp-idf/export.sh"
    else
        error "IDF_PATH not set. Run: source ~/esp/esp-idf/export.sh"
    fi
fi

idf_ver=$(idf.py --version 2>/dev/null | head -1)
info "ESP-IDF: $idf_ver"

# ---- validate port ----
if [ ! -e "$PORT" ]; then
    error "Serial port '$PORT' not found. Available ports:"
    ls /dev/ttyUSB* /dev/ttyACM* 2>/dev/null || echo "  (none)"
    exit 1
fi

info "Target port:  $PORT"
info "Node ID:      $NODE_ID"
info "Firmware dir: $FIRMWARE_DIR"

cd "$FIRMWARE_DIR"

# ---- set target ----
info "Setting target to esp32s3 ..."
idf.py set-target esp32s3

# ---- inject NODE_ID into sdkconfig if changed ----
SDKCONFIG="sdkconfig"
SDKCONFIG_DEFAULT="sdkconfig.defaults"

if [ ! -f "$SDKCONFIG_DEFAULT" ]; then
    cat > "$SDKCONFIG_DEFAULT" <<EOF
# Auto-generated by flash_watch.sh
CONFIG_NODE_ID="$NODE_ID"
CONFIG_WIFI_SSID="Buddhas-Net"
CONFIG_JETSON_IP="192.168.1.100"
CONFIG_UDP_PORT=5500
EOF
    info "Created $SDKCONFIG_DEFAULT with NODE_ID=$NODE_ID"
else
    # Update NODE_ID in existing defaults
    if grep -q "CONFIG_NODE_ID" "$SDKCONFIG_DEFAULT"; then
        sed -i "s/CONFIG_NODE_ID=.*/CONFIG_NODE_ID=\"$NODE_ID\"/" "$SDKCONFIG_DEFAULT"
    else
        echo "CONFIG_NODE_ID=\"$NODE_ID\"" >> "$SDKCONFIG_DEFAULT"
    fi
    info "Updated NODE_ID=$NODE_ID in $SDKCONFIG_DEFAULT"
fi

# Force sdkconfig regeneration from defaults.
# NOTE: This removes any manual configuration changes you have made via
# `idf.py menuconfig`. If you have custom settings, commit them to
# sdkconfig.defaults before running this script, or remove this line and
# manage sdkconfig manually.
[ -f "$SDKCONFIG" ] && rm -f "$SDKCONFIG"

# ---- build ----
info "Building firmware ..."
idf.py build

# ---- flash ----
info "Flashing to $PORT ..."
idf.py -p "$PORT" flash

# ---- monitor (optional) ----
read -rp "$(echo -e "${YELLOW}Open serial monitor? [y/N]:${NC} ")" MONITOR
if [[ "$MONITOR" =~ ^[Yy]$ ]]; then
    info "Opening monitor on $PORT (Ctrl+] to exit) ..."
    idf.py -p "$PORT" monitor
fi

info "Done. Watch '$NODE_ID' is running."
